### ISSUE TITLE
Create login authN page for CLI

### ISSUE THREAD

**Issue by marshallmcdonnell** [smart-spectral-matching/ssm-service-catalog#2]
Modeling how the OpenShift client works, we want to create a login endpoint that could return a message like the following to let you know where the `/oauth/token/request` page is located:

```
$ oc login
You must obtain an API token by visiting https://foo.bar/oauth/token/request
```

This does not have to be a protected endpoint since this is general info.

Maybe `/login`?

**Comment by SmithRWORNL** [comment]
@marshallmcdonnell And presumably if there is no oauth or you presented valid credentials to it, it returns an HTTP OK instead of any message?

**Comment by marshallmcdonnell** [comment]
@SmithRWORNL yes, that sounds good! Except with Username and Password, it won't really "log you in" for now :grin:

**Comment by marshallmcdonnell** [comment]
Closed via https://github.com/smart-spectral-matching/ssm-service-catalog/pull/4
